// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6sqErBldDDXZwAIFRG9cdR9arqflceQ',
    appId: '1:753042715008:web:b269a9fc1c646552745165',
    messagingSenderId: '753042715008',
    projectId: 'nivra-575dc',
    authDomain: 'nivra-575dc.firebaseapp.com',
    storageBucket: 'nivra-575dc.firebasestorage.app',
    measurementId: 'G-VHT9V0L5B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yW3eLHg1foxQQKs-0QZnUR2D8KJtahc',
    appId: '1:753042715008:android:3a4efe35745fe83d745165',
    messagingSenderId: '753042715008',
    projectId: 'nivra-575dc',
    storageBucket: 'nivra-575dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfbJTW29apbZ3HJx2XLRib-a13C5tANw',
    appId: '1:753042715008:ios:64218b658fdcbb80745165',
    messagingSenderId: '753042715008',
    projectId: 'nivra-575dc',
    storageBucket: 'nivra-575dc.firebasestorage.app',
    iosBundleId: 'com.example.nivra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcfbJTW29apbZ3HJx2XLRib-a13C5tANw',
    appId: '1:753042715008:ios:64218b658fdcbb80745165',
    messagingSenderId: '753042715008',
    projectId: 'nivra-575dc',
    storageBucket: 'nivra-575dc.firebasestorage.app',
    iosBundleId: 'com.example.nivra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw6sqErBldDDXZwAIFRG9cdR9arqflceQ',
    appId: '1:753042715008:web:a76c4fbdf0505dce745165',
    messagingSenderId: '753042715008',
    projectId: 'nivra-575dc',
    authDomain: 'nivra-575dc.firebaseapp.com',
    storageBucket: 'nivra-575dc.firebasestorage.app',
    measurementId: 'G-594CFXEG4L',
  );
}
